name: Build and Deploy

on:
  workflow_call:
    inputs:
      node-version-file:
        description: 'Node.js version file path'
        required: false
        default: './.tool-versions'
        type: string
      cache-dependency-path:
        description: 'Path to package-lock.json'
        required: false
        default: './package-lock.json'
        type: string
      build-timeout-minutes:
        description: 'Timeout for build job in minutes'
        required: false
        default: 15
        type: number
      build-command:
        description: 'Build command to run'
        required: false
        default: 'npm run build'
        type: string
      artifact-path:
        description: 'Path to artifact directory'
        required: false
        default: './out'
        type: string
    outputs:
      deployment-url:
        description: 'URL of the deployed application'
        value: ${{ jobs.deploy.outputs.page_url }}

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: ${{ inputs.build-timeout-minutes }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ${{ inputs.node-version-file }}
          cache: 'npm'
          cache-dependency-path: ${{ inputs.cache-dependency-path }}

      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          static_site_generator: next

      - name: Install dependencies
        run: npm ci

      - name: Build and export
        run: ${{ inputs.build-command }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ inputs.artifact-path }}

  deploy:
    environment:
      name: "github-pages"
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    outputs:
      page_url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 