name: Lint

on:
  pull_request:

jobs:
  biome:
    runs-on: ubuntu-latest 
    timeout-minutes: 10
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ./.tool-versions
          cache: 'npm'
          cache-dependency-path: ./package-lock.json
      - run: npm ci
      - run: npm run check

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
