name: Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  quality-check:
    uses: ./.github/workflows/_quality-check.yml
    with:
      timeout-minutes: 10

  build-and-deploy:
    needs: quality-check
    uses: ./.github/workflows/_build-deploy.yml
    with:
      build-timeout-minutes: 15
    permissions:
      contents: read
      pages: write
      id-token: write 